apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kaniko
  labels:
    type: local
spec:
  storageClassName: host-path
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/vagrant/manifests/kaniko/Dockerfiles/"