apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tigera-operator
  namespace: argo-cd  # Argo CD only listen for application type to the argocd installed namespace(argo-cd in this case).So its constant.
spec:
  destination:
    namespace: tigera-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: tigera-operator
    helm:
      valueFiles:
      - values.yaml
    path: manifests/tigera-operator
    repoURL: https://public-helm-repository-20231023095000508500000001.s3.ap-south-1.amazonaws.com/
    targetRevision: v3.26.1
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
    - Validate=false
    - CreateNamespace=true
