apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: google-smon
  labels:
    httpprobecreator/probe: blackbox-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-kubernetes
  jobLabel: google-smon
  endpoints:
    - interval: 10s
      metricRelabelings:
      - action: replace
        sourceLabels:
        - _address_
        targetLabel: __param_target
      - action: replace
        sourceLabels:
        - __param_target
        targetLabel: instance
      - action: replace
        replacement: google-smon
        targetLabel: target
      params:
        module:
        - http_2xx
        target:
        - https://www.google.com