apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2022-08-02T14:55:37Z"
  generation: 5
  labels:
    argocd.argoproj.io/instance: aion-pp
    olympus.cluster: aion
    olympus.cluster.bu: AccountingSaaS
    olympus.cluster.team: aion
    olympus.zone: aws-default-pp-mumbai
    olympus.zone.env: preprod
  name: aion-api-http-health-servicemonitor-aion-pp-health-check
  namespace: aion
  resourceVersion: "3650175878"
  uid: 21ddc4a8-c811-4c75-92d1-b6e7b7af41ee
spec:
  endpoints:
  - interval: 60s
    metricRelabelings:
    - action: replace
      sourceLabels:
      - _address_
      targetLabel: __param_target
    - action: replace
      sourceLabels:
      - __param_target
      targetLabel: instance
    - action: replace
      replacement: aion-pp-health-check
      targetLabel: target
    params:
      module:
      - http_2x
    path: /probe
    port: http
    scheme: http
    scrapeTimeout: 5s
  jobLabel: aion
  namespaceSelector:
    matchNames:
    - zone-monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: olympus-zone-monitoring
      app.kubernetes.io/name: prometheus-blackbox-exporter