{{- if .Values.ingress.enabled }}
{{/*{{- $servicePort := .Values.service.externalPort -}}*/}}
{{/*{{- $ingressExtraPaths := .Values.ingress.extraPaths -}}*/}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "hello-kubernetes.name" . }}
  annotations:
    {{- if eq .Values.ingress.issuer.scope "default" }}
    cert-manager.io/issuer: {{ .Values.ingress.issuer.name }}
    {{- end }}
    {{- if eq .Values.ingress.issuer.scope "cluster" }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer.name }}
    {{- end }}
    {{- if eq .Values.ingress.ingressClassName "internal-nginx" }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "hello-kubernetes.labels" . | nindent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- if .Values.ingress.hosts }}
  tls:
    - hosts:
      {{- toYaml .Values.ingress.hosts | nindent 6 }}
      secretName: {{ .Values.ingress.secretName }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
    {{- $dot := . }}
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: "/"
            pathType: {{ $.Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "hello-kubernetes.name" $dot | quote}}
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
  {{- end }}
