---
# Source: hello-kubernetes/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-kubernetes-release-name
  labels:
    app.kubernetes.io/name: hello-kubernetes
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.10"
