apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: audit-deployment
  name: audit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: audit-deployment
    spec:
      securityContext:
        seccompProfile:
          type: Localhost
          localhostProfile: profiles/audit.json
      containers:
      - image: hashicorp/http-echo:1.0
        name: http-echo
        resources: {}
        args:
        - "-text=just made some syscalls!"
        securityContext:
          allowPrivilegeEscalation: false
status: {}
