apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: default-pod
  name: default-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-pod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: default-pod
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: hashicorp/http-echo:1.0
        name: http-echo
        resources: {}
status: {}
