apiVersion: apps/v1

kind: Deployment

metadata:

  namespace: team-purple

  name: immutable-deployment

  labels:

    app: immutable-deployment

spec:

  replicas: 1

  selector:

    matchLabels:

      app: immutable-deployment

  template:

    metadata:

      labels:

        app: immutable-deployment

    spec:

      containers:

      - image: busybox:1.32.0

        command: ['sh', '-c', 'tail -f /dev/null']

        imagePullPolicy: IfNotPresent

        name: busybox

        securityContext:                  # add

          readOnlyRootFilesystem: true    # add

        volumeMounts:                     # add

        - mountPath: /tmp                 # add

          name: temp-vol                  # add

      volumes:                            # add

      - name: temp-vol                    # add

        emptyDir: {}                      # add

      restartPolicy: Always